### ISSUE TITLE
[eBook] Node.js Basics

### ISSUE THREAD

**Issue by zeucxb** [frontendbr/doe-um-livro#10]
Have you heard about Node.js? You haven't! Node.js is changing how modern applications are built. Companies such as Uber, Walmart, Netflix and Paypal are companies that are using node to create revolutionary applications. Find out why and when Node.js is used and how you can start to benefit from Node.js.

https://leanpub.com/nodejsbasics

**Comment by willianjusten** [comment]
Opa @ZeuCxb, como comentei em outras issues, se pudesse fazer uma descrição do livro, as vezes se gostou dele, o que achou bom, o que ele aborda, só mesmo para não ser muito no escuro. Vlw =D

**Comment by ZeuCxb** [comment]
@willianjusten Não coloquei nada porque no site tem todas as infos de maneira mais organizada 😞

**Comment by vitocaio** [comment]
Excelente estava mesmo procurando algo para nodejs

**Comment by willianjusten** [comment]
@ZeuCxb, copy - paste, as vezes a pessoa já lê e não acha válido ou o contrário, o título não atrai, mas com a descrição, já se atrai =)
