### ISSUE TITLE
[e-book] Orchestrating Docker

### ISSUE THREAD

**Issue by vicainelli** [frontendbr/doe-um-livro#18]
Baixei o livro ontem, ainda não tive tempo de ler, mas já vou compartilhar.

**Conteúdo protegido**

**Comment by LFeh** [comment]
@vicainelli É gratuito?

**Comment by vicainelli** [comment]
Então @LFeh, ele é vendido, porém, o site que estava vendendo, porém, a loja as vezes escolhe 1 livro pra deixar de graça por um tempo, foi quando baixei.

**Comment by LFeh** [comment]
@frontendbr/admins Acham que tudo bem?

**Comment by fdaciuk** [comment]
Acho que pode dar problema sim. Melhor editar o comentário e remover o link. Como o livro é vendido, e em alguns momentos o site deixa gratuito, é para aproveitar aquele momento.

Seria válido se, nesse momento, o site estivesse oferecendo o download gratuito, e fosse adicionado aqui o link **do site de venda**. Mas o livro em si, se é pago, pode dar problema sim.

**Comment by LFeh** [comment]
Sorry @vicainelli

**Comment by vicainelli** [comment]
No problem.
