### ISSUE TITLE
[Londrina - Paraná] JavaScript, Guia do Programador - Maujor (2010)

### ISSUE THREAD

**Issue by willycamargo** [frontendbr/doe-um-livro#21]
# JavaScript, Guia do Programador - Maujor (2010)

Esse foi definitivamente o primeiro livro sobre JavaScript que eu li. Antes dele a linguagem parecia algo de outro mundo pra mim. Não considero o melhor material sobre JavaScript nos dias de hoje (6 anos é muito tempo hehe), mas talvez possa ser útil para alguém
## Apresentação

Apresentação retirada direto do [Site do Livro](http://livrosdomaujor.com.br/javascript/):

> Se você já leu um dos livros escritos pelo Maujor e gostou com certeza vai gostar deste quinto livro de minha autoria. Se não conhece um livro do Maujor este poderá ser um bom começo para conhecer uma de minhas obras.
> 
> Um livro escrito tanto para o desenvolvedor experiente, como o estudante da área relacionada à construção de sites para web. JavaScript - Guia do programador é uma obra que ensina essa linguagem segundo os Padrões Web e pretende ser uma fonte de consulta valiosa no seu dia-a-dia de desenvolvimento.
## Envio

Sou de Londrina - PR. Pode retirar o livro diretamente comigo no local de trabalho se o interessado for daqui (o que acho difícil rs). Faço o envio para outras cidades também, mas não posso bancar o custo de envio.

**Comment by Robsonrrn** [comment]
Oi tudo bom? Me interesso por este livro... você ainda o tem?

**Comment by willycamargo** [comment]
Fala @Robsonrrn , tudo bem sim. Estou com o livro. Consegue entrar em contato comigo no face? Pelo chat é mais fácil combinarmos.

**Comment by Robsonrrn** [comment]
Sim... https://www.facebook.com/robsonrrn

**Comment by ingridrauany** [comment]
Ainda está disponível?

**Comment by willycamargo** [comment]
@ingridrauany ainda disponível. Desculpe pela demora.

**Comment by GlauberF** [comment]
Dísponivel ainda o livro?

**Comment by willycamargo** [comment]
Ainda disponível

**Comment by GlauberF** [comment]
abrange no livro pelo menos o ES5?

**Comment by willycamargo** [comment]
Livro doado

**Comment by DevLarre** [comment]
Olá ainda tem a versão digital do livro?
