### ISSUE TITLE
[Londrina - Paraná] AJAX com jQuery - Maujor (2009)

### ISSUE THREAD

**Issue by willycamargo** [frontendbr/doe-um-livro#23]
# AJAX com jQuery - Maujor (2009)

## Apresentação

Apresentação retirada direto do [Site do Livro](http://livrosdomaujor.com.br/ajaxjquery/):
> Ajax com jQuery é uma poderosa combinação das funcionalidades do AJAX com a simplicidade que jQuery proporciona ao desenvolvimento com JavaScript. Seja você um especialista ou um iniciante no uso de AJAX certamente ficará maravilhado ao descobrir uma metodologia completamente diferente, inovadora, intuitiva e infinitamente mais simples de desenvolver AJAX.

> O primeiro capítulo deste livro apresenta uma visão geral do AJAX segundo a maneira tradicional de desenvolvimento fazendo uma recapitulação dos seus conceitos fundamentais, dissertando sobre os métodos e propriedades do objeto XMLHttpRequest e explicando passo a passo os scripts fundamentais que reunidos formam uma biblioteca mínima para uma requisição AJAX. São estudados ainda os diferentes tipos de arquivos possíveis de serem requisitados e cada caso é ilustrado com um exemplo prático em funcionamento no site do livro.

> No segundo e terceiro capítulos são apresentados e explicados detalhadamente os métodos e funcionalidades da biblioteca JQuery para AJAX. Os capítulos subsequentes são predominantemente práticos contendo exemplos cujo funcionamento pode ser conferido no site do livro.

## Envio

Sou de Londrina - PR. Pode retirar o livro diretamente comigo no local de trabalho se o interessado for daqui (o que acho difícil rs). Faço o envio para outras cidades também, mas não posso bancar o custo de envio.

**Comment by lucianobarauna** [comment]
Fala meu parceiro!!!
Pô estou caçando esse livro rsrs sou do rio de janeiro, como podemos ver isso ?
Abrcs

**Comment by willycamargo** [comment]
Te adicionei no facebook. Vamos conversar por lá.

**Comment by lucianobarauna** [comment]
Livro doado !!!! chegou hoje !!
Vlw parceiro !!!

**Comment by Mendrone** [comment]
Sensacional! Valeu @lucianobarauna pelo feedback e @willycamargo pela doação!

**Comment by LFeh** [comment]
💃
