### ISSUE TITLE
[Londrina] CSS Avançado

### ISSUE THREAD

**Issue by ortizvinicius** [frontendbr/doe-um-livro#24]
Livro bem completo de CSS dos autores Joseph R. Lewis e Meitar Moscovitz.
É perfeito para iniciantes e muito bom também pra quem já é profissional e quer aprimorar seus conhecimentos (pois é bem completo mesmo).

Confissão: O que estou falando é o que vi por cima, ganhei num evento e nunca li :P, mas o livro é muito bom.

Esse é o link da editora pra saber mais detalhes: http://novatec.com.br/livros/css/

Trabalho perto do correio, então se alguém de fora quiser pagar o frete eu envio.

**Comment by leticia0805** [comment]
Eu quero!
Moro em São Paulo, como podemos combinar direitinho?

**Comment by ortizvinicius** [comment]
@leticia0805 Vc mora na capital? Tem aquele esquema de frete a cobrar, você sabe como funciona?

**Comment by leticia0805** [comment]
Sim, sou da capital, se quiser mandar por PAC a cobrar é sucesso

**Comment by ortizvinicius** [comment]
@leticia0805 Blz, manda seus dados no vinicius.oaw@gmail.com, vou ver como funciona
