### ISSUE TITLE
[São Paulo] - Aplicações Node

### ISSUE THREAD

**Issue by highlabs** [frontendbr/doe-um-livro#26]
Estou doando esse livro: http://www.novatec.com.br/livros/node-mongodb/

**Construindo Aplicações Node com MongoDB e Backbone**
_Prototipação rápida e implantação escalável_

Na verdade eu não li e esta encostado em casa. :) Quem quiser da um toque.

Posso entregar na região da Paulista e Butantã.

Quem tiver interessado, só comentar aqui.
Se morar em outra cidade e bancar o frete, eu envio também.

**Comment by EdipoNascimento** [comment]
@highlabs 

Boa tarde! Eu tenho interesse no livro citado.

**Comment by highlabs** [comment]
@EdipoNascimento Blz, cara? Como você quer retirar? Em mãos?

**Comment by EdipoNascimento** [comment]
Blz.. Consegue me enviar pelos correios? Eu pago o frete?

**Comment by highlabs** [comment]
Me manda email com seus dados: daniel@oshi.ro

**Comment by EdipoNascimento** [comment]
Fetio...

Atte,.

**Comment by LFeh** [comment]
Se resolverem fechem a issue :)
