### ISSUE TITLE
[São Paulo - S.B.Campo] Apostila de Java - Caelum

### ISSUE THREAD

**Issue by marquinhusgoncalves** [frontendbr/doe-um-livro#27]
Bom fiz o curso presencial de Java na Caelum e tenho as 3 apostilas que gostaria de estar fazendo a doação.
- Java e Orientação a Objetos;
- Java para Desenvolvimento Web;
- Laboratório Java com Testes, JSF e Design Patterns

As apostilas são ótimas e bem didáticas, tudo bem explicado para desenvolver um projeto mesmo, muitos exemplos e ilustrações.

Quem aceitar a doação pode retirar ou entrar em contato para que possamos acertar o envio. (Custos de envio fica por conta de quem receberá).

Twitter: @marquinhusgonc

**Comment by marnescassule** [comment]
De onde você é???
Eu sou de SP e estou interessado nos materiais

**Comment by leticia0805** [comment]
Também me interesso, caso ainda esteja disponível.

**Comment by marquinhusgoncalves** [comment]
@marnescassule sou de S.B.Campo e trabalho em Alphavile, você prefere retirar ou quer que eu te envie? me envia um e-mail eu@marquinhusgoncalves.com
@leticia0805 vou tentar entregar para quem entrou em contato primeiro, caso não dê certo eu entro em contato com você e damos continuidade ok.

**Comment by lorenascimentoo** [comment]
Olá @marquinhosgoncalves se ainda houver disponibilidade de livros, estou interessada. =]

**Comment by marquinhusgoncalves** [comment]
@leticia0805 o primeiro(a) interessado não entrou em contato, então como você é a próxima por favor entre em contato para tentarmos fazer essa entrega... me envia um e-mail eu@marquinhusgoncalves.com Fico no aguardo.

**Comment by marquinhusgoncalves** [comment]
Apostilas postadas para @leticia0805 ...
Assim que chegar por favor close issue.
Bons estudos.

**Comment by leticia0805** [comment]
Chegaram direitinho! :)
Valeus :)

**Comment by LFeh** [comment]
🌞
