### ISSUE TITLE
[São Paulo] Livro - Use A Cabeça (iniciação Rápida) Ajax 2ª Edição

### ISSUE THREAD

**Issue by andrewsfg** [frontendbr/doe-um-livro#28]
## Descrição
Não agüenta mais criar sites Web que são recarregados sempre que um usuário move o mouse? Cansado de servidores que esperam para responder a solicitações de usuários em busca de ingressos para o cinema? Parece que você precisa de um pouco de Ajax (ou talvez muito) em sua vida. A programação assíncrona lhe permitirá transformar seus sites em aplicativos agradáveis, inventivos e ágeis que farão seus usuários se sentirem como se tivessem voltado à supervia de informações em vez de estar parados em uma rede de discagem congestionada...

## Envio
Posso entregar em alguma estação de metrô (moro próximo ao metrô Carrão, da linha vermelha) fora do horário comercial ou enviar por correios. Meu e-mail é andrewsfg@gmail.com ;)

**Comment by rafaDfaria** [comment]
Para não pegar por pegar o livro e tirar a oportunidade de alguém que possivelmente faria melhor uso dele do que eu, tenho uma pergunta.

Como ainda estou cursando a faculdade, Ciências da Computação e preciso pular o estágio pela questão salarial, preciso me preparar muito bem para concorrer a uma vaga de Junior mesmo sem experiência prévia no mercado de trabalho da área.
Peguei um guia de estudo no freecodecamp, (o qual pode ser conferido no único repositório que tenho no github, [Tracking Study](https://github.com/rafaDfaria/Study/blob/master/CHECKLIST.md), e estou estudando por ele com o objetivo de conseguir uma vaga de Junior em Front End. 

Acredita que este livro será uma boa adição ao meu plano de estudos, ou um profissional mais experiente faria melhor uso dele?

**Comment by andrewsfg** [comment]
@rafaDfaria Olá, tudo bem? Eu não li o livro inteiro, então, de repente não posso opinar muito. Ele não me pareceu tão didático lendo as primeiras páginas e eu precisava me dedicar mais, preferi começar com outros livros e acabei não chegando nesse. Não sei se ajudei muito no comentário, mas é isso.

**Comment by raulfernando** [comment]
Se o @rafaDfaria não ficar com ele eu gostaria de ficar

**Comment by andrewsfg** [comment]
Pessoal, algumas pessoas me pediram por email antes, pra envio por Correios. Estou aguardando a resposta delas para saber se vão querer mesmo. Aí, se eles desistirem, falo com vocês aqui. Abraços!

**Comment by raulfernando** [comment]
Blz

**Comment by andrewsfg** [comment]
Agradeço a todos interessados, mas o primeiro email que recebi no dia, já pegou o livro. 

Abraços =)

**Comment by LFeh** [comment]
Boa @andrewsfg :D
