### ISSUE TITLE
[Salvador BA] Desenvolvendo com AngularJS

### ISSUE THREAD

**Issue by clarabatt** [frontendbr/doe-um-livro#30]
## Sobre o Livro
Ganhei o livro de um amigo a um tempo, não cheguei realmente a ler e como está parado gostaria de passar adiante. Para mais informações, segue o link da editora para ver o sumário.
[Site da Editora](https://www.novatec.com.br/livros/desenvolvendo-com-angularjs/)

## FRETE
Se você é de outra cidade, posso enviar, frete por conta do interessado.

**PS: Não seja como eu, aceite se realmente for ler.** :laughing:

**Comment by luisrbferreira** [comment]
Olá Clara, tenho interesse no livro, moro em Salvador mesmo.

**Comment by DanyelDan** [comment]
Boa tarde  ClaraBatt!
Não sei se vc já doou o livro de angular, mas caso ainda o tenha e queira doar, gostaria muito de recebê-lo, pois estou precisando muito estudar AngularJs. Sou de Salvador e poderia pegar em algum shopping, como por exemplo o shopping da Bahia.

**Comment by clarabatt** [comment]
@DanyelDan Já vou passar pro @luisrbferreira :/
