### ISSUE TITLE
[Salvador BA] Guerreiro SEO

### ISSUE THREAD

**Issue by clarabatt** [frontendbr/doe-um-livro#31]
## Sobre o Livro
O livro é bom, tem uns métodos ultrapassados, mas a essência se mantém, é legal pra entender a lógica por trás do SEO, tem um **caráter bastante técnico**. 
Para mais informações, segue o link da editora para ver o sumário:
[Site da Editora](https://novatec.com.br/livros/guerreiro-seo/)

## FRETE
Se você é de outra cidade, posso enviar, frete por conta do interessado.

**Comment by luisrbferreira** [comment]
Olá Clara, tenho interesse no livro, moro em Salvador mesmo. Tenho interesse no livro de Angular JS também que você anunciou.

**Comment by rhenanteix** [comment]
Ainda está com o livro?

**Comment by clarabatt** [comment]
Infelizmente não, já vou passar pro @luisrbferreira.
