### ISSUE TITLE
[Indaiatuba] - Livros de Java, PHP, Design, POO, Design Patterns, etc

### ISSUE THREAD

**Issue by femontanha** [frontendbr/doe-um-livro#39]
Olá pessoal tudo bem?
Estou com alguns livros parados em casa e gostaria de doa-los.

Pra ficar mais fácil eu postei os livros no meu Instagram (https://www.instagram.com/fellipeazambuja/)
Vou priorizar por "ordem de chegada" (quem mandar um direct primeiro)

Por favor só mandem o seu "interesse" no direct do Instagram, vou só responder por lá!
Valeu =)

**Comment by lucenarenato** [comment]
Bom dia, voce tem o livro de php ainda?

**Comment by femontanha** [comment]
Olá ja foram todos! Vou fechar o tópico obrigado!

**Comment by lucenarenato** [comment]
por nada!
