### ISSUE TITLE
Alguns livros

### ISSUE THREAD

**Issue by ZeuCxb** [frontendbr/doe-um-livro#4]

**Comment by LFeh** [comment]
@ZeuCxb Deu algum problema ai...

**Comment by ZeuCxb** [comment]
Eu vi

**Comment by ZeuCxb** [comment]
@LFeh a internet aqui deu pau no meio do envio, já estou arrumando isso.

**Comment by LFeh** [comment]
Abre as issues separadamentes. 

Outra coisa, lembre-se que só pode compartilhar ebooks gratuitos ;)

**Comment by ZeuCxb** [comment]
@LFeh saquei, foi mal então rsrs, achei que valia os que tenho aqui da casa do código 👎

**Comment by LFeh** [comment]
hahaha, @ZeuCxb iriamos ter problemas com pirataria :p

**Comment by ZeuCxb** [comment]
@LFeh só vale pt-br? Só Front?

**Comment by LFeh** [comment]
Cara, vamos focar em Front ou áreas afins. Pode ser em inglês também.
