### ISSUE TITLE
[Maringá] Livro HTML5 e CSS3, domine a web do futuro 

### ISSUE THREAD

**Issue by guuibayer** [frontendbr/doe-um-livro#40]
Adquiri o livro a um bom tempo, ele realmente me serviu muito bem com sua ótima introdução sobre as tecnologias mencionadas com capitulos específicos sobre animações, responsividade e possui até uma breve introdução a pré-processadores CSS. 

Aqui você pode encontrar o [sumário](https://www.casadocodigo.com.br/pages/sumario-html-css) onde ele explica mais detalhadamente o que é abordado.
- Ele possui apenas algumas manchas apenas na capa frontal, [confome imagens ](https://i.imgur.com/j4Gfmwr.jpg)
- Pode retirar comigo **Maringá - PR**, ou frete por conta. 
- Alguns detalhes
  - Número de páginas: 228
  - Data publicação: 05/2012

**Comment by marnescassule** [comment]
Eu querooooi

**Comment by guuibayer** [comment]
Já doei esse aqui, porém ainda tenho o #42 disponível, caso alguém tenha interesse pode entrar em contato pelo 43 99609-2506
