### ISSUE TITLE
[Maringá] Livro Javascript o guia definitivo 6ª edição

### ISSUE THREAD

**Issue by guuibayer** [frontendbr/doe-um-livro#41]
Sinceramente não li o livro inteiro, acredito que serve um pouco como referência pra consulta também, explica legal a base da linguagem, falando sobre seus tipos, DOM, eventos, expressões regulares, funções, classes e prototypes e até aborda em seu último capítulo algumas API's do HTML5 como Web Workers, Geolocation e bancos no cliente.

- A capa dele está com uma mancha como na imagem, mas nada demais com as páginas, [confome imagens ](https://i.imgur.com/xg3BPbS.jpg)
- Pode retirar comigo **Maringá - PR**, ou frete por conta. 
- Alguns detalhes
  - Esse livro é a 6ª edição.
  - Número de páginas: 1062
  - Data publicação: 2013

**Comment by marnescassule** [comment]
Eu quero os dois....

**Comment by luka-rmar** [comment]
Já foi doado o livro?

**Comment by guuibayer** [comment]
Estou com ele ainda, caso alguém queira pode chamar no whats 43 996092506

**Comment by robertofilho1** [comment]
Cara vc já doou o livro?

**Comment by guuibayer** [comment]
Olá @robertofilho1, doei o livro hoje pela manhã e acabei esquecendo de atualizar
