### ISSUE TITLE
[São Paulo] - JavaScript Guia ado Programador

### ISSUE THREAD

**Issue by laugustofrontend** [frontendbr/doe-um-livro#43]
## Descrição  do livro
Este livro aborda os fundamentos da linguagem, desde os conceitos mais básicos de programação web até as funcionalidades de emprego da linguagem segundo os conceitos de orientação a objetos. É uma referência abrangente dos recursos da linguagem. Descreve detalhadamente objetos, construtores, métodos, funções, propriedades

## Opnião Pessoal
Ótimo livro do grande mestre Maujor, ele aborda todas as funcionalidades da linguagem, mostrado exemplos de como funcionar cada método, função, arrays e objetos, ótimo para iniciantes em javascript, pois terá uma ótima base sobre o javascript.

- Entrega preferencialmente pessoal em São Paulo, caso seja necessário envio por conta de quem solicitar o livro.

![photo_2018-10-06_14-35-37](https://user-images.githubusercontent.com/7988674/46572440-04d45a80-c95c-11e8-84f2-78eb9848c072.jpg)

#### Importante

**Não promova a pirataria.**

Apenas eBooks GRATUITOS e disponíveis na web para esse fim podem ser compartilhados.

**Comment by NiltonJansenn** [comment]
Boa tarde! 
Tenho interesse ,pode por favor me enviar via correio ,para pagamento de quem for retirar o livro.

**Comment by laugustofrontend** [comment]
Me passe os seguintes dados que estarei vendo como fazer esse tipo de envio

Nome Completo
Endereço
Bairro
CEP
