### ISSUE TITLE
[São Paulo] CSS Cookbook

### ISSUE THREAD

**Issue by laugustofrontend** [frontendbr/doe-um-livro#45]
## Descrição do Livro
Aprenda a resolver problemas reais encontrados com CSS. Este livro de receitas oferece centenas de exemplos práticos para a utilização de CSS na formatação de suas páginas web e inclui exemplos de código que podem ser utilizados imediatamente. Você encontrará exatamente o que você precisa, desde o básico, até hacks e gambiarras complexas aos problemas que se apresentam.

Cada receita explica como customizar uma solução que satisfaça as suas necessidades, e cada capítulo apresenta um modelo de design que exibe os tópicos discutidos. Você aprenderá sobre o comportamento dos navegadores mais recentes – incluindo o IE 8, Firefox 3, Safari 4 e o Google Chrome – e como conciliar as diferenças no modo em que esses navegadores exibem suas páginas web. Organizada em um formato conveniente, de fácil utilização como referência, esta edição é uma companheira valiosa para qualquer pessoa que esteja trabalhando com CSS.

## Opnião Pessoal
Ótimo livro para consulta sobre propriedades que ser esta com dúvidas de como funcionar, eu aprendi muito lendo esse livro, e fazendo os exemplos que são apresentados.

- Entrega preferencialmente pessoal em São Paulo, caso seja necessário envio por conta de quem solicitar o livro.

![photo_2018-10-06_14-35-45](https://user-images.githubusercontent.com/7988674/46572528-b88a1a00-c95d-11e8-80da-2164773d1b69.jpg)

#### Importante

**Não promova a pirataria.**

Apenas eBooks GRATUITOS e disponíveis na web para esse fim podem ser compartilhados.

**Comment by peter0021** [comment]
Boa Noite!! veja para o frete 55375-000.
