### ISSUE TITLE
[eBook]  Understanding ECMAScript 6

### ISSUE THREAD

**Issue by diogomoretti** [frontendbr/doe-um-livro#5]
Apenas uma ótima dica de leitura ;)

Enjoy =]

**[READ](https://leanpub.com/understandinges6/read)**

**Comment by willianjusten** [comment]
Fiquei em dúvida @diogomoretti , você tem o ebook para doar, é só uma dica? Seria legal a pessoa escrever algo mais na descrição, para que os outros entendam.

**Comment by diogomoretti** [comment]
Apenas dica de leitura. Talvez o título do repo não esteja tão apropriado, mas fiz como as primeiras issues #1 e #3, que são dicas também...

**Comment by willianjusten** [comment]
Então cara, o título do repo é "Doe um livro", então a ideia é que sejam doados livros físicos entre as pessoas ou ebooks **gratuitos**. Dicas são legais, mas desvirtuam com o sentido e proposta do repositório.

**Comment by willianjusten** [comment]
Se reparar, tanto o #1 quanto o #3 são livros gratuitos =)

**Comment by LFeh** [comment]
@diogomoretti Coloca no https://github.com/frontendbr/forum/issues/229

**Comment by diogomoretti** [comment]
@willianjusten, esse que postei também é gratuito para leitura na web. Se você quiser, pode comprar o livro físico.

**Comment by willianjusten** [comment]
De fato...erro meu de num ter reparado que depois de um loading, o livro aparecia logo abaixo (interface escrota essa hein -.-).

Só para num poluir essa issue mais do que está, poderia abrir uma nova com o livro E um indicativo que pode ler o livro no site com uma descrição do mesmo?
