### ISSUE TITLE
 [São Paulo] Livro Web Design Responsivo - Caelum

### ISSUE THREAD

**Issue by daniellucindo** [frontendbr/doe-um-livro#6]
Pessoal,
Estou com esse livro novo ( No Plástico ) que ganhei no Front in Sampa 2016 se alguém quiser ou conhecer alguém que esteja iniciando seus estudos seria uma boa leitura =)

**Comment by twobanks** [comment]
@daniellucindo ué, eu moro em Uberaba-MG...se tivesse como enviar via Correios, eu pagaria o frete.

**Comment by cmpereirasi** [comment]
Muito show @daniellucindo

**Comment by willianjusten** [comment]
Peço só que quando conseguirem doar o livro, fechem a issue =D
E meus parabéns @daniellucindo pela boa vontade ^^

**Comment by leticia0805** [comment]
Eu sou de São Paulo! Tenho interesse. Você consegue entregar em alguma estação do metrô?

**Comment by daniellucindo** [comment]
Opa 
Imaginei que não seria tão rápido.
Pow quem quiser tira um 2 ou 1 hehehe #zueira

Leticia você vai querer mesmo?
Trabalho na Berrini e moro na Parada Inglesa Zona Norte então qualquer estação nessas linhas posso te entregar.

Caso você não queira e não aparece mais ninguém ( iniciante ) o destino desse livro será Uberaba-MG.

=)

**Comment by leticia0805** [comment]
Tudo bom, Daniel?

Eu vou querer sim!
Me interesso bastante pelos cursos da Caelum, mas o preço sempre me deixa
com o pé atrás xD

Costumo passar sempre na linha verde e azul, é só me falar o horário e dia
que for melhor pra ti que eu me organizo pra ir buscar o livro!

Em 15 de julho de 2016 17:11, Daniel Lucindo <notifications@github.com>
escreveu:

**Comment by daniellucindo** [comment]
Leticia,
Passa seus contatos pra alinhar a entrega :)

**Comment by leticia0805** [comment]
Meu celular: 9 5242-5449
Pode chamar no whats que respondo rápido

Em 18 de jul de 2016 11:35, "Daniel Lucindo" <notifications@github.com>
escreveu:

**Comment by Mendrone** [comment]
@leticia0805 @daniellucindo posso fechar a issue?

**Comment by leticia0805** [comment]
Pode sim :)
Já marcamos a entrega do livro

Em 18 de jul de 2016 16:20, "Vitor Mendrone" <notifications@github.com>
escreveu:

**Comment by willianjusten** [comment]
Eu fiquei na dúvida, não deveria fechar somente quando o livro fosse entregue? Ou já marcado pode fechar?

**Comment by LFeh** [comment]
Good question. 

Podemos reabrir se der problema... o que acha?

**Comment by daniellucindo** [comment]
Pode Ser Feh =)

**Comment by daniellucindo** [comment]
O Livro já esta em boas mãos :)

**Comment by willianjusten** [comment]
Show =)
