### ISSUE TITLE
[eBook] JSbooks - The best free JavaScript resources

### ISSUE THREAD

**Issue by ericdouglas** [frontendbr/doe-um-livro#8]
http://jsbooks.revolunet.com/

**Comment by willianjusten** [comment]
Fala aí @ericdouglas , esse link de fato é bem legal, mas como comentei até em outra issue, seria legal ao invés de só o link, uma descrição mínima do que é e talz, só para complementar. As vezes até uma dica de qual livro, se já tiver lido algo, nesse caso que é um conjunto de livros.

**Comment by ericdouglas** [comment]
@willianjusten beleza cara :smile: 

Vou fechar essa issue porque não faz sentido mesmo com o propósito do repo, melhor ser pontual nas recomendações.

**Comment by ericdouglas** [comment]
ps: seria legal adicionar no README essa informação de fazer um breve comentário sobre o porquê da indicação do livro.

**Comment by LFeh** [comment]
@ericdouglas Consegue arrumar o README?

**Comment by ericdouglas** [comment]
@LFeh feito [aqui](https://github.com/frontendbr/doe-um-livro/pull/13).

**Comment by willianjusten** [comment]
Já aceitei =)
