### ISSUE TITLE
[eBook] InfoQ eMag: A Próxima Geração de HTML5 & JavaScript

### ISSUE THREAD

**Issue by wellingtongeek** [frontendbr/doe-um-livro#9]
[InfoQ eMag: A Próxima Geração de HTML5 & JavaScript](https://www.infoq.com/br/minibooks/emag-html5-javascript#minibookDownload)

O desenvolvedor web moderno precisa conhecer muito mais do que antes e não pode ficar parado. Esta eMag procura ser um guia nessa direção. Na seleção de artigos do InfoQ, temos a colaboração dos desenvolvedores que constroem as aplicações web mais avançadas usando as tecnologias mais recentes.

**Comment by dionmauricio** [comment]
Muito obrigado pela contribuição do livro, valeu mesmo
